name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install (npm)
        run: npm i

      - name: Build
        run: rm -rf build.example && npm run build:example

      - name: Setup git
        run: |
          git config user.email "vfleurit@gmail.com"
          git config user.name "valflrt"

      - name: Push
        run: |
          git add build.example
          git commit -a -m "Automatic example build" && git push

      - name: Deploy
        run: npm run deploy:gh-pages
