name: build

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install (npm)
        run: npm i

      - name: Setup git
        run: |
          git config --global user.email "vfleurit@gmail.com"
          git config --global user.name "valflrt"
          git remote set-url origin https://valflrt:${{ secrets.SSH_KEY }}@github.com/valflrt/${{ github.event.repository.name }}.git

      - name: Build and Deploy
        run: npm run deploy:gh-pages
