name: build

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install (npm)
        run: npm i

      - name: Build and Deploy
        run: npm run deploy:gh-pages
